### ISSUE TITLE
Section for interested attendees to leave their email address

### ISSUE THREAD

**Issue by tjmkruger** [MarkPearl/Website_DevConf#5]

**Comment by tjmkruger** [comment]
I was thinking to call the Google Drive api and write to a csv.  That way the file is there on record and accessible by everybody.

**Comment by MarkPearlCoZa** [comment]
Another option would be to use MadMimi - we have an account through the DeveloperUG?

**Comment by tjmkruger** [comment]
Included in pull request #8  :)
