### ISSUE TITLE
Put together a CFP for speakers

### ISSUE THREAD

**Issue by MarkPearlCoZa** [MarkPearl/Website_DevConf#6]

**Comment by MarkPearlCoZa** [comment]
Note, message from Simon Stewart regarding CFP.  

Cool, we can chat next week at Discovery?

When the CFP does out, send me links so I can RT from @CodeSkills, @JSinSA.

**Comment by MarkPearlCoZa** [comment]
www.papercall.io
www.papercall.io/DevConf

**Comment by MarkPearlCoZa** [comment]
Great suggestions for submitting a CFP.

http://conferences.oreilly.com/strata/hadoop-big-data-eu/public/cfp/425?imm_mid=0dd5af&cmp=em-data-confpro-na-stuk16_em1_cfp#tips

**Comment by MarkPearlCoZa** [comment]
As mentioned, holy wall of text batman! That is a lot of reading before submitting. 
- Downloading a txt file to complete is weird for me, much rather complete webform 
- Most people struggle to suggest 1 topic, asking to submit 2 or 3 is a stretch especially in SA where there are so few speakers. 
- Process mechanics section implies I've either done this talk before or that I know how this talk will go. In reality most people submit and only start planning once they've been accepted. 
- The other big item is that you just know that someone will cry foul that speaker submissions aren't blind and "fair".

**Comment by rmaclean** [comment]
Vote to close this. can include the suggestions in 2017
