### ISSUE TITLE
Change the conference date

### ISSUE THREAD

**Issue by tjmkruger** [MarkPearl/Website_DevConf#9]
I updated the date on the website.

Still to be updated:
- Sponsors document

**Comment by MarkPearlCoZa** [comment]
Did you mean to make a pull request.

**Comment by tjmkruger** [comment]
Yes sorry got distracted, will do it from home.

On Wednesday, 09 December 2015, Mark Pearl notifications@github.com wrote:

> Did you mean to make a pull request.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarkPearl/Website_DevConf/issues/9#issuecomment-163240862
> .

## 

Kind Regards

Terence Kruger
@tjmkruger
